/** GENERATED by scripts/gen-permissions-matrix.mjs — do not edit.
 *
 *  Source: the public.permission_catalog seed in supabase/migrations
 *  (20261005120000_permission_module.sql and later). The database table is
 *  the authority for WHAT may be asked of can_record(); RLS and the definer
 *  RPCs named in `enforcingObject` are the authority for the ANSWER. This
 *  module is documentation data for the Command Center matrix and the
 *  handbook — never a gate. Regenerate: npm run gen:permissions. */

export interface PermissionMatrixCells {
  owner: string
  command: string
  member: string
  inactive: string
}

export interface PermissionCatalogRow {
  /** can_record() action, e.g. `edit`; role-level rows use kind `*`. */
  action: string
  kind: string
  area: string
  rule: string
  enforcingObject: string
  testId: string | null
  matrix: PermissionMatrixCells
  sortOrder: number
}

export const PERMISSION_CATALOG: PermissionCatalogRow[] = [
  { action: "work", kind: "*", area: "Work cases / registries (own bureau)", rule: "Any active CID profile; bureau match, JTF, lead/creator, command, explicit grant or joint assignment for a case.", enforcingObject: "private.is_active / private.can_access_case_row", testId: "rls", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 10 },
  { action: "delete", kind: "*", area: "Delete registry records (with Undo)", rule: "Bureau Lead or higher (rank only) on a record SIB has not hidden.", enforcingObject: "private.can_delete + private.siu_hidden", testId: "rls", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 20 },
  { action: "archive", kind: "*", area: "Archive / restore a case", rule: "Command (Bureau Lead+); an active legal hold blocks archiving.", enforcingObject: "public.case_archive / public.case_restore", testId: "v130", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 30 },
  { action: "permanent_delete", kind: "*", area: "Permanently delete an archived case", rule: "Owner only, after a catalog-derived preview and a reasoned confirm; cases with legal requests refuse.", enforcingObject: "public.case_delete_preview / public.case_permanent_delete", testId: "v130", matrix: { owner: "✓ (reason + preview required)", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 40 },
  { action: "assign_role", kind: "*", area: "Approve members / assign roles", rule: "The unified assignment matrix: a Bureau Lead within their bureau below their rank; DD/Director anywhere.", enforcingObject: "private.can_assign_cid_role", testId: "v116", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 50 },
  { action: "announce", kind: "*", area: "Post announcements", rule: "Command with audience authority (everyone: Deputy Director+; a bureau: its Lead or DD+).", enforcingObject: "private.can_announce + private.can_post_audience", testId: "rls", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 60 },
  { action: "feedback_submit", kind: "*", area: "Submit feedback", rule: "Any active member.", enforcingObject: "feedback_ins", testId: "rls", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 70 },
  { action: "feedback_triage", kind: "*", area: "View ALL feedback + triage/catalog", rule: "Owner; members see their own submissions only.", enforcingObject: "feedback_meta_all / feedback_sel", testId: "rls", matrix: { owner: "✓", command: "✗", member: "own only", inactive: "✗" }, sortOrder: 80 },
  { action: "audit_read", kind: "*", area: "Audit Log", rule: "Owner only — including PERMISSION_DENIED rows written by private.perm_deny.", enforcingObject: "audit_sel", testId: "rls", matrix: { owner: "✓", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 90 },
  { action: "handbook", kind: "*", area: "Developer Handbook (in-app)", rule: "Owner only.", enforcingObject: "client route gate + useAuth().isOwner", testId: "e2e", matrix: { owner: "✓", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 100 },
  { action: "owner_console", kind: "*", area: "Owner Console", rule: "Owner only.", enforcingObject: "private.is_owner", testId: "rls", matrix: { owner: "✓", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 110 },
  { action: "grant_ownership", kind: "*", area: "Grant ownership (is_owner flag)", rule: "SQL only — guard_profile makes is_owner immutable from every client.", enforcingObject: "trigger guard_profile", testId: "rls", matrix: { owner: "SQL only", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 120 },
  { action: "read", kind: "case", area: "Read a case", rule: "Case access, or the SIB read superset (oversight / agent read of a CID case).", enforcingObject: "private.can_read_case", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 200 },
  { action: "access", kind: "case", area: "Work a case", rule: "Case access: bureau match, JTF, lead/creator, command, explicit grant, joint or SIB standing on an SIB case.", enforcingObject: "private.can_access_case", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 210 },
  { action: "edit", kind: "case", area: "Edit a case (not archived)", rule: "Case access while the case is not archived.", enforcingObject: "private.can_access_case + cases.archived_at", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 220 },
  { action: "archive", kind: "case", area: "Archive a case", rule: "Command, case not archived, no active legal hold.", enforcingObject: "public.case_archive", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 230 },
  { action: "restore", kind: "case", area: "Restore an archived case", rule: "Command, case archived.", enforcingObject: "public.case_restore", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 240 },
  { action: "grant_access", kind: "case", area: "Grant case access", rule: "The case lead, or command.", enforcingObject: "private.can_grant_case", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "lead of case", inactive: "✗" }, sortOrder: 250 },
  { action: "delete_child", kind: "case", area: "Delete case material (reports, evidence, tasks…)", rule: "Rank AND reach: Bureau Lead+ with case access; SIB command on an SIB investigation.", enforcingObject: "private.can_delete_case_child", testId: "v180", matrix: { owner: "✓*", command: "✓ with case access", member: "✗", inactive: "✗" }, sortOrder: 260 },
  { action: "permanent_delete", kind: "case", area: "Permanently delete a case", rule: "Owner only, and only an archived case.", enforcingObject: "private.is_owner + cases.archived_at", testId: "v180", matrix: { owner: "✓ (armed)", command: "✗", member: "✗", inactive: "✗" }, sortOrder: 270 },
  { action: "read", kind: "report", area: "Read a report", rule: "Read access to the parent case.", enforcingObject: "reports_sel → private.can_read_case", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 300 },
  { action: "edit", kind: "report", area: "Edit a report", rule: "Case access on the parent case (finalized contents stay trigger-locked).", enforcingObject: "reports_upd → private.can_access_case", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 310 },
  { action: "delete", kind: "report", area: "Delete a report", rule: "Rank AND reach on the parent case.", enforcingObject: "reports_del → private.can_delete_case_child", testId: "v180", matrix: { owner: "✓*", command: "✓ with case access", member: "✗", inactive: "✗" }, sortOrder: 320 },
  { action: "read", kind: "evidence", area: "Read evidence", rule: "Read access to the parent case.", enforcingObject: "evidence_sel → private.can_read_case", testId: "v180", matrix: { owner: "all", command: "bureau / global", member: "case access", inactive: "✗" }, sortOrder: 330 },
  { action: "delete", kind: "evidence", area: "Delete evidence", rule: "Rank AND reach on the parent case.", enforcingObject: "evidence_del → private.can_delete_case_child", testId: "v180", matrix: { owner: "✓*", command: "✓ with case access", member: "✗", inactive: "✗" }, sortOrder: 340 },
  { action: "read", kind: "legal", area: "Read a legal request", rule: "Creator, participants, Owner, AG oversight, the bureau prosecutor lanes, judges for the judicial queue, CID case members for standard classification; sealed requests are undiscoverable.", enforcingObject: "private.can_view_legal_request", testId: "legal", matrix: { owner: "✓", command: "participant / case member (standard)", member: "participant / case member (standard)", inactive: "✗" }, sortOrder: 400 },
  { action: "edit", kind: "legal", area: "Edit a legal draft", rule: "The creator, while the request is a draft or returned.", enforcingObject: "private.can_edit_legal_draft", testId: "legal", matrix: { owner: "creator", command: "creator", member: "creator", inactive: "✗" }, sortOrder: 410 },
  { action: "approve", kind: "legal", area: "Decide the CID gate of a legal request", rule: "Not the creator; case access; the responsible bureau's Lead (JTF: any Lead), DD/Director/Owner fallback; SIB command on an SIB case.", enforcingObject: "private.can_approve_legal", testId: "legal", matrix: { owner: "fallback", command: "responsible bureau (JTF any)", member: "✗", inactive: "✗" }, sortOrder: 420 },
  { action: "read", kind: "person", area: "Read a person record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "persons_sel → private.is_active + private.siu_hidden", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 500 },
  { action: "edit", kind: "person", area: "Edit a person record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "persons_upd", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 510 },
  { action: "delete", kind: "person", area: "Delete a person record", rule: "Bureau Lead or higher, unless SIB has hidden the record.", enforcingObject: "persons_del → private.can_delete", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 520 },
  { action: "read", kind: "vehicle", area: "Read a vehicle record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "vehicles_sel", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 530 },
  { action: "edit", kind: "vehicle", area: "Edit a vehicle record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "vehicles_upd", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 540 },
  { action: "delete", kind: "vehicle", area: "Delete a vehicle record", rule: "Bureau Lead or higher, unless SIB has hidden the record.", enforcingObject: "vehicles_del → private.can_delete", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 550 },
  { action: "read", kind: "gang", area: "Read a gang record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "gangs_sel", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 560 },
  { action: "edit", kind: "gang", area: "Edit a gang record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "gangs_upd", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 570 },
  { action: "delete", kind: "gang", area: "Delete a gang record", rule: "Bureau Lead or higher, unless SIB has hidden the record.", enforcingObject: "gangs_del → private.can_delete", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 580 },
  { action: "read", kind: "place", area: "Read a place record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "places_sel", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 590 },
  { action: "edit", kind: "place", area: "Edit a place record", rule: "Any active member, unless SIB has hidden the record.", enforcingObject: "places_upd", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 600 },
  { action: "delete", kind: "place", area: "Delete a place record", rule: "Bureau Lead or higher, unless SIB has hidden the record.", enforcingObject: "places_del → private.can_delete", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 610 },
  { action: "read", kind: "account", area: "Read an account record", rule: "Any active member, unless SIB has blocked the record.", enforcingObject: "accounts_sel → private.siu_blocked", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 620 },
  { action: "edit", kind: "account", area: "Edit an account record", rule: "Any active member, unless SIB has blocked the record.", enforcingObject: "accounts_upd", testId: "v180", matrix: { owner: "✓", command: "✓", member: "✓", inactive: "✗" }, sortOrder: 630 },
  { action: "delete", kind: "account", area: "Delete an account record", rule: "Bureau Lead or higher, unless SIB has blocked the record.", enforcingObject: "accounts_del → private.can_delete", testId: "v180", matrix: { owner: "✓*", command: "✓", member: "✗", inactive: "✗" }, sortOrder: 640 },
]

/** The Command Center / Owner Console table shape (one row per catalog entry). */
export interface PermissionsMatrixRow extends PermissionMatrixCells {
  /** Stable key: `${action}/${kind}`. */
  key: string
  area: string
  kind: string
}

export const PERMISSIONS_MATRIX: PermissionsMatrixRow[] = PERMISSION_CATALOG.map((r) => ({
  key: `${r.action}/${r.kind}`, area: r.area, kind: r.kind, ...r.matrix,
}))

export const MATRIX_NOTE =
  "* Owner rights on division data come from the owner account ALSO holding a command role — ownership itself only grants the owner-only areas. Enforcement: profiles.is_owner → private.is_owner() in RLS (audit_log, feedback, feedback_meta) + useAuth().isOwner in the UI. The guard_profile trigger makes is_owner immutable from every client — granting it is a SQL/dashboard operation."
