'use client'

/** Court-packet / instrument print sheet for a legal request. Renders the
 *  SAME document spec the PDF and DOCX exports build (lib/legalExport) —
 *  meta grid, sections, signature lines — so the on-screen print can never
 *  disagree with a downloaded copy. A print is a screen copy: it is not
 *  recorded in legal_export_log and carries no verification code (the spec
 *  says so in its Verification section); Export PDF/DOCX are the verified
 *  paths. Same mechanics as cases/tabs/WarrantPrint: a portal-mounted paper
 *  sheet, @media print swaps the app out, afterprint unmounts it. */
import { useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import type { PdfDocSpec } from '@/lib/pdf'

/** Screen-hidden; @media print swaps the app out and the sheet in. Plain
 *  serif/black-on-white CSS (not the dark tokens) — this is paper, not UI. */
const PRINT_CSS = `
.legal-print-sheet { display: none; }
@page { margin: 16mm; }
@media print {
  body > *:not(.legal-print-sheet) { display: none !important; }
  .legal-print-sheet { display: block !important; background: #fff; color: #111; font: 11pt/1.5 Georgia, 'Times New Roman', Times, serif; }
  .legal-print-sheet .lp-lh { text-align: center; border-bottom: 3px double #111; padding-bottom: 10pt; margin-bottom: 12pt; }
  .legal-print-sheet .lp-state { margin: 0; font-size: 9pt; letter-spacing: 0.3em; text-transform: uppercase; }
  .legal-print-sheet .lp-div { margin: 1pt 0 6pt; font-size: 10pt; letter-spacing: 0.14em; text-transform: uppercase; }
  .legal-print-sheet h1 { margin: 0 0 2pt; font-size: 16pt; text-transform: uppercase; letter-spacing: 0.06em; }
  .legal-print-sheet .lp-sub { margin: 0; font-size: 8pt; letter-spacing: 0.12em; text-transform: uppercase; color: #333; }
  .legal-print-sheet table { width: 100%; border-collapse: collapse; font-size: 10pt; }
  .legal-print-sheet th, .legal-print-sheet td { border: 1px solid #888; padding: 3pt 6pt; text-align: left; vertical-align: top; }
  .legal-print-sheet th { font-size: 8.5pt; text-transform: uppercase; letter-spacing: 0.08em; background: #eee; }
  .legal-print-sheet .lp-kv td:first-child { width: 34%; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.06em; color: #333; }
  .legal-print-sheet .lp-meta { margin-bottom: 12pt; }
  .legal-print-sheet section { margin-bottom: 10pt; break-inside: avoid; }
  .legal-print-sheet h2 { margin: 0 0 4pt; font-size: 10pt; text-transform: uppercase; letter-spacing: 0.1em; border-bottom: 1px solid #111; padding-bottom: 2pt; }
  .legal-print-sheet .lp-para { margin: 0 0 4pt; white-space: pre-wrap; }
  .legal-print-sheet .lp-empty { color: #555; }
  .legal-print-sheet .lp-sigs { display: flex; gap: 24pt; margin-top: 24pt; }
  .legal-print-sheet .lp-sig { flex: 1; border-top: 1px solid #111; padding-top: 3pt; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.08em; color: #333; }
  .legal-print-sheet footer { margin-top: 14pt; border-top: 1px solid #888; padding-top: 4pt; text-align: center; font-size: 8pt; color: #444; }
}
`

function LegalPacketSheet({ spec, preparedAt }: { spec: PdfDocSpec; preparedAt: string }) {
  return (
    <div className="legal-print-sheet">
      <style>{PRINT_CSS}</style>
      <header className="lp-lh">
        <p className="lp-state">State of San Andreas</p>
        <p className="lp-div">Department of Justice · Judiciary</p>
        <h1>{spec.docType}</h1>
        <p className="lp-sub">{spec.refCode}{spec.subtitle ? ` · ${spec.subtitle}` : ''}</p>
      </header>
      <table className="lp-kv lp-meta"><tbody>
        {spec.meta.map(([k, v]) => (
          <tr key={k}><td>{k}</td><td>{v || <span className="lp-empty">—</span>}</td></tr>
        ))}
      </tbody></table>

      {spec.sections.map((sec) => (
        <section key={sec.title}>
          <h2>{sec.title}</h2>
          {sec.headers && sec.rows ? (
            sec.rows.length ? (
              <table>
                <thead><tr>{sec.headers.map((h) => <th key={h}>{h}</th>)}</tr></thead>
                <tbody>
                  {sec.rows.map((row, i) => (
                    <tr key={i}>{row.map((cell, j) => <td key={j}>{cell || <span className="lp-empty">—</span>}</td>)}</tr>
                  ))}
                </tbody>
              </table>
            ) : <p className="lp-para lp-empty">None on file.</p>
          ) : (
            (sec.paras?.length ? sec.paras : ['—']).map((t, i) => <p key={i} className="lp-para">{t}</p>)
          )}
        </section>
      ))}

      {spec.signatures?.length ? (
        <div className="lp-sigs">
          {spec.signatures.map((label) => <div key={label} className="lp-sig">{label}</div>)}
        </div>
      ) : null}

      <footer>Generated by the CID Portal · prepared {preparedAt} · For official use — court presentation copy.</footer>
    </div>
  )
}

/** Mounts the paper sheet, opens the (blocking) print dialog a paint later,
 *  and calls onDone on afterprint so the caller can unmount it. */
export function CourtPacketPrint({ spec, preparedAt, onDone }: {
  spec: PdfDocSpec
  preparedAt: string
  onDone: () => void
}) {
  // onDone is usually an inline closure — hold it in a ref so a parent
  // re-render (e.g. realtime) can never re-run the mount effect and re-open
  // the print dialog.
  const doneRef = useRef(onDone)
  useEffect(() => { doneRef.current = onDone }, [onDone])
  useEffect(() => {
    const done = () => doneRef.current()
    window.addEventListener('afterprint', done)
    // Let the portal paint before the (blocking) print dialog opens.
    const t = window.setTimeout(() => window.print(), 50)
    return () => { window.clearTimeout(t); window.removeEventListener('afterprint', done) }
  }, [])
  return createPortal(<LegalPacketSheet spec={spec} preparedAt={preparedAt} />, document.body)
}
