/** Shared entity UI (Portal Improvements plan, Phase 2 — P2-07). */
export { EntityPicker } from './EntityPicker'
export type { EntityPickerProps, EntitySuggestFn } from './EntityPicker'
export { DuplicatePanel } from './DuplicatePanel'
export type { DuplicatePanelProps } from './DuplicatePanel'
export { ComparePanel } from './ComparePanel'
export type { ComparePanelProps } from './ComparePanel'
export { EntityCreateSheet, DUPLICATE_DEBOUNCE_MS } from './EntityCreateSheet'
export type { EntityCreateSheetProps, SheetSubmitResult } from './EntityCreateSheet'
export { MergeDialog, MergeDialogPanel, mayMerge } from './MergeDialog'
export type { MergeDialogProps, MergeApi } from './MergeDialog'
export { MergeHistory, MergeHistoryPanel } from './MergeHistory'
export type { MergeHistoryProps } from './MergeHistory'
export { SuggestedUpdates, SuggestedUpdatesPanel } from './SuggestedUpdates'
export type { SuggestedUpdatesProps } from './SuggestedUpdates'
export { ObservationForm } from './ObservationForm'
export type { ObservationFormProps } from './ObservationForm'
