/** Generates src/components/guide/guideContent.ts from docs/USER-GUIDE.md so
 *  the in-app User Guide stays synchronized with the repo doc. Run
 *  `npm run gen:guide` after editing docs/USER-GUIDE.md — CI fails if the
 *  generated module drifts from the markdown.
 *
 *  Transform (the in-app renderer, src/lib/markdown, has no --- rules or
 *  italics): drop the doc's `# …` title, drop `---` rules, unwrap italic
 *  spans (full-line first so bold-inside-italics survives), escape the
 *  template-literal metacharacters. */
import { readFileSync, writeFileSync } from 'node:fs'

const SRC = 'docs/USER-GUIDE.md'
const OUT = 'src/components/guide/guideContent.ts'

let md = readFileSync(SRC, 'utf8')

md = md
  .replace(/^#\s[^\n]*\n+/, '') // doc title — the app supplies its own chrome
  .replace(/^---$\n?/gm, '') // horizontal rules
  .replace(/^\*(?!\*)(.+)\*$/gm, '$1') // full-line italics (may contain **bold**)
  .replace(/(?<![*\\])\*(?!\*)([^*\n]+)\*(?!\*)/g, '$1') // inline italics
  .replace(/\n{3,}/g, '\n\n')
  .trim()

const escaped = md.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

writeFileSync(
  OUT,
  `/** The in-app copy of docs/USER-GUIDE.md, adapted for src/lib/markdown
 *  (no --- rules or italics). GENERATED by scripts/generate-guide.mjs —
 *  edit docs/USER-GUIDE.md and run \`npm run gen:guide\`. */
export const USER_GUIDE_MD = \`${escaped}
\`
`,
)
console.log(`wrote ${OUT} from ${SRC}`)
