/** The in-app copy of docs/USER-GUIDE.md, adapted for src/lib/markdown
 *  (no --- rules or italics). GENERATED by scripts/generate-guide.mjs —
 *  edit docs/USER-GUIDE.md and run `npm run gen:guide`. */
export const USER_GUIDE_MD = `Welcome to the **CID Portal**, the live investigative case-management system for the San Andreas Criminal Investigation Division and the Special Investigations Bureau. This is the operational manual: what each workspace is, how to get access, and how to run your work day to day.

Everything in the portal is **live and shared** — when a colleague updates a record, your screen follows within seconds. What you can see and do depends on your **active membership, department, rank, assignment and, where it applies, compartment**. Every rule is enforced by the server: if a record is not yours to see, it simply is not there, and no interface trick can reach it.

## A. Choose your workspace

The portal serves several kinds of user. Each signs in the same way but lands in a different working world:

| You are… | Your workspace |
|---|---|
| **CID member** | The full CID portal — cases, intelligence registries, legal requests, command surfaces. Your bureau (Major Crimes or Street Crimes) and rank decide what is yours to run. |
| **SIB member** | The SIB workspace **plus** the full CID portal. The Special Investigations Bureau is a separate investigative authority with its own chain of command; an active SIB member also works CID cases as an ordinary investigator. |
| **Intelligence-only submitter** | A submission interface for SAHP, BCSO and LSPD personnel — send information, evidence and patrol intelligence to investigators. No access to cases or registries. |
| **Command member** | Everything a CID member has, plus the Command Center — personnel approvals, promotions, chain of command, duty status. |
| **Legal reviewer** (Prosecutor, Attorney General, Judge) | The legal dossier workspace. Reviewers receive only the **legal packet** an investigator selected — never the rest of the case. |

Screens and actions appear only where your standing supports them. A button you cannot use is not hidden as a favour — the server would refuse it anyway.

### The bureaus

CID's investigative work is organized into three bureaus, plus one temporary designation:

- **Major Crimes Bureau (MCB)** — serious, violent and complex investigations.
- **Street Crimes Bureau (SCB)** — gang, narcotics and firearms work, surveillance, repeat offenders and proactive enforcement.
- **Special Investigations Bureau (SIB)** — sensitive, organized, undercover and high-level investigations, compartmented under its own chain of command (section E). SIB membership is appointed, never applied for.
- **JTF** — not a bureau: a temporary joint-case designation a case carries while more than one bureau works it.

LSPD, BCSO and SAHP are external field **agencies** — police departments that submit intelligence to CID (see section F) — not CID bureaus.

## B. Your first five minutes

### Signing in

1. Open the portal — you land on the **Secure Access** screen.
2. Pick a way in: **Continue with Discord** (most members), **Continue with Google**, or type your email for a one-time **Email link**.

> **Access denied?** If Command has denied your login you'll see the reason instead of a request form. Contact Command if you believe it's a mistake.

### Requesting the right access

After first sign-in the portal asks **"What do you need access for?"**:

- **Join CID** — an application for investigative access. Fill in your display name, badge number, permanent bureau (Major Crimes or Street Crimes — JTF is a per-case designation, never a home bureau, and SIB is appointed rather than applied for), the CID role you're requesting, and a short reason. **Requesting grants nothing** — Command reviews it, and can approve, approve with a different role, send it back for correction (you'll see the note, edit, and resubmit), or reject. You stay locked out until approved.
- **Submit Intelligence** — for SAHP, BCSO and LSPD personnel. Enter your agency, callsign/badge, rank and unit; this becomes your reporting identity on every submission. Access is **available straight away** — no queue.

SIB is **not** applied for here. SIB membership is appointed from inside the division.

### Set yourself up

- Open **My Profile** (your name card at the bottom of the sidebar): display name, badge number, avatar, Discord link for DMs. Your work is attributed by display name and badge.
- The **Appearance** tab holds your accent colour and comfortable/compact density (saved on this device).
- **LOA**: click **Set LOA** in the header before leave. It is informational — you can still sign in — but sign-off routing automatically goes around you while it's set.

### Where the work is

- **My Desk** (Command section — your landing page) gathers everything waiting on you: sign-offs, returned cases, due follow-ups, open tasks, mentions, followed records and draft reports. Start every session here.
- The **Action Center** is one prioritized queue of everything awaiting a decision or action from you, in named lanes — Overdue, Returned to you, Needs your action, Command decisions, **Unassigned intel** (field intelligence no reviewer has claimed), **Expiring BOLOs** (windows closing within 7 days), Waiting on others, and **Drafts** (unfinished work you saved — resume or discard). Every item says why it's here and what to do next; filter the queue by type or bureau.
- The **bell** is your notification feed. Notifications about the same case or request collapse into one group; the unread badge is exact. Click a row to mark it read and jump to its record, mark a whole group read, or **Mark all read** in one click. The bell's settings panel can **mute the optional streams** (announcements, tracker authorizations, document suggestions, stale-case reminders, sign-off heads-ups) — assignments, mentions, sign-off decisions, legal and security notices can never be muted. Duplicate notifications for the same event are suppressed automatically.

## C. Navigation

### The CID sidebar

Five categories (a bottom bar on your phone). Click a category to jump to its first screen; a sub-tab strip under the header switches between the screens inside it.

| Category | Screens |
|---|---|
| **Command** | My Desk, Action Center, Dashboard, Analytics, Announcements, Heatmap, Roster & Commendations |
| **Cases** | Case Files, Operations, Legal Requests, Attachments, RICO |
| **Investigative Tools** | One workspace holding all fourteen intelligence tools — see below |
| **Reference** | Penal Code, SOPs & Library, User Guide |
| **Oversight** | Calendar, Shift Reports, Audit Log |

The Developer Handbook (Reference) and the Audit Log's full history are owner-level surfaces — most members will not see them.

### The Investigative Tools workspace

All fourteen intelligence tools live behind the single **Investigative Tools** item. It opens on a **directory** of the tools in three groups — Intelligence Records (Persons, Gangs, Places, Vehicles, Accounts, Indicators), Operational Tools (BOLO Board, Intelligence, Media Vault, Records) and Analysis (Network, Narcotics, Ballistics, M.O. Detector). Each card names the tool, says what it holds, and shows a live count of what your access can see.

- **Open several at once.** Click a tool and it opens as a **tab** in a strip under the header. Open as many as you need — Persons beside Vehicles beside the BOLO Board — and click between them instantly. Persons and Vehicles also open **individual records as their own tabs**, so two profiles can sit side by side.
- **Nothing resets when you switch.** Every open tab stays loaded — your search, filters and scroll position are exactly where you left them when you come back. The **Directory** chip returns you to the tool list without closing anything.
- **Close what you're done with.** Every tab has an ✕; right-click a tab for **Close others** / **Close all**; drag tabs to reorder them. A tab with unsaved work asks before it closes.
- **On your phone** the strip collapses to the current tool plus an **Open tabs** menu — switch between or close your tabs from there.
- **Old links still work.** Bookmarks, notifications and cross-links to the old addresses (a saved \`/persons\` link, a person or vehicle deep link) open the right tool — or the right record — inside the workspace automatically.

Your open tabs are remembered for your sign-in session and restored when you return to Investigative Tools; a record your access can no longer see simply does not reopen.

### The SIB sidebar

SIB is a **separate workspace and authority**, not a CID category. An SIB account's sidebar leads with the **Unit** category (the SIB Workspace) and then carries CID's entire navigation, tab for tab — the same screens, including the same Investigative Tools workspace, scoped to what SIB standing may see and touch. Shared registries (Persons, Vehicles, Gangs, Places, Accounts, Indicators, Media…) are **one master dataset for the whole platform**; only the department context and labels differ.

### The header, everywhere

- **Search everything…** — press **/** to focus, or **Ctrl-K / ⌘K** for the palette. One search reaches everything your access can see: cases, reports, case tasks, evidence, operations, legal requests, persons, **BOLOs**, gangs, places, vehicles, accounts, narcotics, ballistics, documents, penal charges, **intelligence submissions** and **division members**. Results come grouped by kind, each row tagged with what it is (typo-tolerant — a few letters or a plate fragment is enough). Opening a person, vehicle, gang or narcotics hit lands it as its own record tab in the Investigative Tools workspace; a task hit deep-links straight to its case's Tasks tab. The palette also runs commands: **Go to** any screen your role can actually open (Owner, Command and SIB surfaces are simply not listed otherwise), a permission-gated **New record** set, My active cases, Set/Clear LOA and Sign out. On a phone the palette opens full-screen.
- **+ Create** — one button for every record type you're allowed to create: case, person, vehicle, gang, place, account, indicator, operation and (for SIB agents) SIB investigation. It opens the exact same forms the individual screens use, from anywhere — a bottom sheet on your phone. Types your role can't create aren't shown.
- **Bell** — notifications (see section B). **Access chip** — hover to see what your role allows. **Set LOA / Clear LOA**. **Sign out**.

### Pins and recents — "Jump back in"

- **Pin** a case or record (the pin button on case headers and record profiles) to keep it one click away. Pins are saved to your account, so they **follow you across devices**. Pinning stores only the record's id — never its contents.
- The portal also keeps a short **recently-opened** trail on each device.
- Both appear in the **Jump back in** strip on the Command dashboard — pinned chips first, then recents, with a **Clear** for the history. A record you can no longer access simply doesn't appear; a pin comes back by itself if your access returns.

## D. Running a CID case

### Create it

**Cases → Case Files → New Case.** Title, bureau and summary — or a template chip that prefills them (templates with a numbered checklist also seed the Tasks tab). The case gets an auto-numbered ID (like \`SCB-5000041\` — Major Crimes cases are \`MCB-4…\`, Street Crimes \`SCB-5…\`) and appears for your bureau instantly. Cases opened before the bureau restructure keep their original numbers (\`LSB-\`, \`BCB-\`, \`SAB-\`, \`SIU-\`) — a case number is a permanent identifier.

### Staff it

- The **lead investigator** owns the case; **supporting officers** are added as assignments and counted on the case header.
- The **responsible bureau** decides whose Bureau Lead reviews the case's legal requests; command can reassign it from the case header when a case changes hands.
- **Joint cases:** when more than one bureau is involved, the lead or Command clicks **Make This a Joint Case**. The case keeps its origin and gains a **JTF** tag; members from other bureaus get a temporary joint-case role (Case Lead, Co-Lead, Joint Investigator, Support Investigator, Liaison or Read-Only) and, optionally, an access expiry. That grants access to this case only — permanent bureau and rank never change. **End Joint-Case Status** closes all temporary access at once; every step is logged.

### Track it

A case carries four separate dials — don't conflate them:

- **Status** — the record state: \`open → active → cold → closed\` (drag the board card or change it on the case).
- **Priority** — low / medium / high / critical.
- **Investigative stage** — a deliberate progress marker moved with a reason: Intake → Active Investigation → Legal Process → Enforcement Ready → Pending Closure → Closed.
- **Workflow** — where the case sits in sign-off (investigation, awaiting sign-off, returned, closed).

**Hover any status chip, anywhere in the portal** — the tooltip says what that status means and, where a workflow is waiting, who acts next. The same vocabulary is used everywhere, so "Returned for changes" on a case always means the same thing it does on a legal request.

The case header is two compact lines — identity, state and **one recommended next action** on the first; stage, unit, lead, last update, sign-off and overdue markers on the second. Blockers show in the metric strip below, legal-hold and archived states as banners. Rarely-used and administrative actions live in the header's **Actions** menu.

Under the header, a **Health** row lists advisory chips when the case looks neglected — no lead detective, no summary, quiet 14+ days, overdue tasks, draft reports, returned legal work, undescribed evidence. Each chip's tooltip says why it raised and how to clear it, and clicking one jumps to the relevant section. Health chips are **advisory only** — they never block sign-off or closure — and a healthy case shows no row at all.

### Work the tabs

The case detail groups its tabs into three areas. Each section pill carries a **live count** of what's inside (reports, media, tasks, charges, legal, intel…) and an amber **attention dot** when something in it needs someone — a report awaiting sign-off, an actionable legal request, an overdue task, a draft report. **Switching sections never loses your place**: every section you've visited keeps its filters, drafts, scroll position and half-finished forms until you leave the case, and the Brief's "since your last visit" recap is only reset when you actually leave the case — not by hopping between tabs. On a phone, a compact section switcher replaces the tab strip.

**Investigation**
- **Brief** — the case at a glance: assignments, stats, recap, blockers.
- **Intel & Notes** — working notes plus the case's linked persons, gangs, places and narcotics. This is the one place links are added or removed.
- **Surveillance** — observations, association events and trackers tied to the case.
- **Extractions** — records pulled from devices and accounts.
- **Timeline** — every event on a zoomable chronology band: scroll to zoom, drag to pan, hover a dot.
- **Graph** — the case as a link chart. Suspects, vehicles, gangs, places, evidence and reports orbit the case, joined by labelled relationships. Drag to arrange (kept per case), click a node for details, dashed lines mark inferred connections.

**Evidence & case record**
- **Photos & Media** — the case's photographs in a gallery and its video, audio, documents and links as compact records, each with its evidence number, category, uploader, time, linked report and access state. Archived items stay out of the default view but are never lost.
- **Charges** — the charge sheet. An authorized investigator adds a charge and it is **active immediately** — no internal command approval step. Filing with the court, conviction and dismissal are recorded by the court-side authorities, not by CID.
- **RICO** — appears once enterprise tracking is enabled from the Brief (or when the case already carries RICO data).
- **Reports** — investigative reports. See section I.

**Coordination & closure**
- **Legal** — the case's warrants and subpoenas, grouped by who acts next. See section G.
- **Tasks** — the checklist, with owners and due dates.
- **Sign-off** — submit the finished investigation for command review. See section I.
- **Chat** — the case room, with @mentions.

### Close it — and reopen it

Closure runs through **Sign-off** (section I). Cases are never deleted from the working view: Command **archives** (archived cases can be restored), and only the portal owner can permanently delete. A closed case can be reopened by changing its status if your rank allows; sealed reports inside it stay sealed.

### Manage the list — saved views and bulk actions

- **Saved views.** On Case Files (and the Persons, Legal Requests and BOLO lists), set up your filters, scope and search, then **Save** them as a named view. Views are saved to your account — they follow you across devices — and one view per list can be marked **default**, applying automatically when you open the list clean. Rename or delete views from the same menu. Case views you had saved on this device before are migrated to your account automatically the first time you open Case Files.
- **Needs attention** (command). The case-age filter includes a **Needs attention** option for command: open cases carrying at least one health flag the list can see (no lead, no summary, quiet 14+ days, follow-up date passed). List rows carry a small attention count whose tooltip names the flags.
- **Bulk actions.** Select several cases (checkboxes; shift-click for a range) and **set status** (open / active / cold), **assign a lead** (command only), or **archive / restore**. Every bulk action shows a preview confirm first, skips rows you can't edit (the result says how many), and reports progress as it works through the selection. Closing a case still runs through Sign-off, one case at a time — and there is **no bulk delete**, ever.

## E. Running an SIB investigation

The Special Investigations Bureau investigates matters that cannot run through the ordinary chain — public corruption, law-enforcement integrity, organized crime, internal leaks — under its own authority. Need-to-know is the default posture.

### Roles and chain of command

| Rank | Authority |
|---|---|
| **Special Agent in Charge** (conventionally "X-1") | Operational head — unit command, intake dispositions, access decisions, legal review |
| **Senior Special Agent** | Senior field tier |
| **Special Agent** | Field agent |
| **Oversight** (the Attorney General, ex officio) | Departmental oversight and standard-classification investigations — no field authority |

Callsigns (X-1, X-2…) are display conventions, never authority. The portal owner administers the unit but holds no operational role. The Director of CID has **no** SIB standing — they may request sight of a specific investigation (below) and may restrict or reveal records, nothing more.

### Open an investigation

Work enters SIB three ways:

1. **Referrals** — from the confidential **Report a Concern** door (any member, outside the ordinary chain), or referred from the Intelligence review queue. Accepting a referral opens a **preliminary inquiry** unless you decide otherwise.
2. **Direct** — an agent opens an investigation in the SIB Workspace.
3. **Assuming control** — SIB command can assume control of an existing CID case without moving, copying or renumbering anything; **Return control to CID** hands it back with its bureau, lead and full history intact.

Every investigation carries a **classification** — who inside SIB may reach it:

- **SIB** — any active agent.
- **SIB Restricted** — assigned agents and SIB command.
- **SIB Command** — command plus an explicit allow-list.
- **SIB Compartmented** — allow-list only; rank does not exempt anyone, X-1 included.

A **preliminary inquiry** stays invisible to oversight at every classification until it becomes a **full investigation**. Categories (corruption, integrity, organized crime, narcotics…) are subject matter, orthogonal to classification.

Wherever a record carries an access level — an SIB classification here, a legal classification on a request, a classification on an SOP document — it renders as the same style of **access badge**; hover it to see who can reach the record.

### Staff and share it

- **Assign agents** to the investigation; compartmented work also needs the compartment grant.
- **Supporting access** lets a named CID officer into one investigation's case file — never into SIB's sources, intelligence or operations — for up to 30 days.
- **Conflicts and recusal:** a declared conflict removes that agent's access immediately, at any rank; only a different member of command can clear it.
- **The Director's window:** the Director of CID can request access to a specific investigation by case number from My Desk. X-1 decides; approval opens that one case file for a fixed period.

### Targets, intelligence and the watchlist

The SIB Workspace tabs carry the unit's own material: **Targets** (designations and priorities), **Intelligence**, **Operations**, **Watchlist** (persons, vehicles, gangs, places, accounts or indicators under watch, each with a review clock — a watch never runs more than a year without a decision), and **Tradecraft** (sources, undercover, financial, communications, integrity, exports). Exports always withhold confidential source identities, undercover legends and intercept content.

### Shared registries — and what SIB may hide

SIB reads and writes the **same** Persons, Gangs, Vehicles, Places, Accounts and Indicators registries CID uses. When an entry must not be visible to CID:

- **Restrict to SIB** (on the record's profile) offers two modes: **Restrict Entire Record** — the record disappears from CID's view entirely — or **Restrict Selected Intelligence Only** — CID keeps the record but the selected sections go dark. The dialog shows exactly what CID currently has attached, warns when CID-authored material would be affected (and asks you to acknowledge it), and requires a written reason. The reason is visible only inside SIB.
- **Compartments** (SIB Workspace) lists everything SIB has taken out of CID's view and everything given back, including the **"Origin not established"** queue — records flagged for a human decision about whether they are SIB or ordinary CID material. Nothing is reclassified by guesswork.
- **Reveal to CID / Released to CID** — a restriction can be lifted for everyone, for one case, or for one officer; releases of items (intelligence, reports, evidence, media, targets, summaries, warnings) carry a handling level and are tracked in the **Released to CID** tab.

Restricting and revealing are reserved to SIB agents of any rank, the Director, and the portal owner. Oversight can read what its standing allows but cannot restrict or reveal.

To a CID viewer, a restricted record is simply **not there** — an ordinary "not found", with no hint that anything was withheld.

### SIB inside CID

An **active** SIB member works CID as an ordinary investigator: reading and editing CID cases, filing reports, adding tasks and charges, using every registry. This requires no CID role, and ends the moment the SIB membership is suspended, removed or the account deactivated. It does **not** carry owner-level administration — permanent deletion, role management and security policy remain the owner's.

The reverse is not true: CID members see nothing of SIB's investigations, targets, sources, notes or watchlist, and nothing about what has been restricted.

### Close it

Closing an investigation records a closure reason — arrest/prosecution, referred to CID, referred to DOJ, administrative action, unfounded, insufficient evidence, intelligence only, merged, or inactive.

## F. Intelligence intake

All incoming information — from patrol, detectives, surveillance or outside agencies — lands in one place: **Intelligence** (Investigative Tools → Intelligence). A submission is information: it never becomes a case, a registry record or a verified fact by itself. A reviewer decides what it means.

### Submitting

- **Intelligence-only submitters** (SAHP/BCSO/LSPD) get a focused interface: **Home · Submit Intelligence · My Reports · Drafts**. Their agency, callsign, rank and unit ride on every submission.
- **Investigators** author the same structured record with **+ New intelligence** on the review screen.

A submission describes **what was involved**: add a **Person**, **Vehicle**, **Gang / MC**, **Location** or **Item / Seizure**, attach evidence and media, and state the basis for each claim — I saw this myself, someone told me, or not stated. A summary and a jurisdiction (Los Santos / City or Blaine County) are required to send.

The submitter can follow their report's life: **Draft → Sent → Being reviewed → Question for you → Reviewed / Being acted on / Filed, no action**. A reviewer's question opens a thread with the officer; internal review notes are never shown to the submitter.

### Reviewing

Every active CID member sees every field submission — jurisdiction is where the events happened, not a routing rule, and no bureau owns the queue. The review queue offers All / Unclaimed / Mine / Assigned / Needs info / per-jurisdiction / Processed / Archived views. A reviewer:

1. **Takes** the record (or releases it back; command can assign a handler — the assignment history is kept).
2. Checks **Seen before** — the repeat signal against earlier submissions.
3. **Verifies each claim**: Verified, Unverified, Disputed or Rejected. Reliability grades the source; a verdict grades one claim.
4. **Matches** a claim to an existing person, vehicle, gang or place — asserting they're the same thing without editing either record.
5. **Acts** where warranted: open a case from the record, link it to an existing case, cite it as a surveillance observation, or register a confidential source.
6. **Decides**: record urgency and reliability, archive with a reason (no investigative value, duplicate, resolved elsewhere, outdated, unable to corroborate, retained for reference), or — command only — delete. Deleted records can be restored only by the portal owner.

### Referral to SIB

A reviewer can flag **possible SIB relevance**, then **Refer to SIB** with a category (organized crime, gang enterprise, narcotics or firearms trafficking, public corruption, fugitive, major crime, cross-jurisdiction, other). SIB accepts or declines, and assigns its own Special Agent — SIB work follows the SIB chain, and a Bureau Lead cannot make that assignment. A public-corruption referral restricts the report immediately; the referrer is warned first.

## G. Legal requests — warrants and subpoenas

Legal work lives in **Cases → Legal Requests** and on each case's **Legal** tab. CID and SIB requests follow **different review chains**; both end with the same fulfilment discipline.

### Draft and packet (both lanes)

1. **File Warrant Request** or **File Subpoena** (or start from a finalized arrest-warrant report). For a warrant, pick **Arrest** (needs a suspect from Persons) or **Search** (a subject **and/or** search targets — places, postal areas, vehicles — plus the items sought). Your justification is the probable cause.
2. On the draft's **Packet** tab, select the exhibits reviewers should see — evidence, attachments, finalized reports, media, links. **Reviewers receive only the packet, never the case.** Alongside it they see a minimal case brief: number, title, status, stage and bureau.
3. **Submit.** A packet preview cross-checks your selected items against their live sources and flags anything missing or unfinalized before you confirm. Drafts autosave on your device; a **Restore draft** banner appears if your browser closed mid-edit.

### The CID chain

\`\`\`
Investigator → CID command review → Prosecutor queue → Prosecutorial review → Judicial review → Issue → Execute / Serve → Return / Comply → Close
\`\`\`

- **CID command review.** The responsible bureau's **Bureau Lead** reviews — and so, at any time, can a **Deputy Director, the Director, or the portal owner**, from any bureau, with no waiting or hand-off step. On a **JTF** case any Bureau Lead may act. Nobody reviews their own request. When command stands in for the home Bureau Lead, the record says so — the review history names who acted and the rank they held **at the time**. Decisions: approve, deny, or return for revision (with a note).
- **Prosecutor queue.** Approved requests enter the queue for the bureau's covering **prosecutors** — coverage is granted by the Attorney General. A prosecutor **claims** a request (conflicts of interest are barred automatically); a **sealed** request cannot be claimed and is assigned by the Attorney General directly.
- **Prosecutorial review.** The assigned prosecutor approves (onward to a Judge), returns it for correction, or declines it.
- **Judicial review.** A **Judge** claims (or, for sealed requests, is assigned), then approves — with conditions and an expiry where warranted — denies, or returns. A judge never issues the instrument.
- **Returns and resubmission.** Any return reopens the draft with the reviewer's note. If a **Judge or prosecutor** returned it and your fix is **not a material change**, resubmission goes straight back to the prosecutor queue. Declare a **material change** and it re-enters full CID command review — the declaration is yours to make honestly, and it is logged.
- **Issue and fulfil.** Once approved, an authorized CID officer records **issue**, then **execution and return** (warrants) or **service and compliance** (subpoenas). Materials received under a subpoena are logged back to the case. An approved arrest warrant can be pushed to the in-city **MDT** as a WANTED flag with no details visible.
- **Close / withdraw / revoke.** The creator can withdraw before a decision. Revoking an issued instrument requires the assigned Judge, DOJ management or the owner, with a reason.

### The SIB chain

\`\`\`
Special Agent → X-1 review → Attorney General → Judge (where judicial approval is required)
\`\`\`

An SIB request never enters the CID review lane or the bureau prosecutor queue. SIB command (X-1 — or the investigation's lead agent) reviews first; approval goes to the **Attorney General**, then to a **Judge**. Notifications stay inside the unit; if no SIB commander is available the Attorney General is alerted — never CID command. Nobody, X-1 included, reviews their own request.

### Sealed requests

A sealed request is visible only to the people directly involved. It cannot be claimed from any queue — prosecutors and judges reach it only by explicit assignment.

## H. Records and intelligence

The registries — every tool in the **Investigative Tools** workspace (section C) — are one shared, deconflicted dataset:

- **Persons** — suspects and persons of interest. A profile carries identity, warrants, vehicles, properties, linked cases, media and notes, with a dossier export.
- **BOLO Board** — at-large subjects, fed by approved arrest warrants and BOLO flags.
- **Gangs** — organizations, ranks, members, properties and turf.
- **Places** — locations and production processes.
- **Vehicles** — plates, owners, gang ties; the registry flags plates that surface across cases.
- **Accounts** — social-media and online accounts, handle history and ownership.
- **Indicators** — burner phones, bank accounts, serials, aliases, addresses. The same value on two cases raises a **deconfliction alert** naming both; a case you can't access shows as restricted — coordinate through its bureau lead.
- **Intelligence** — the intake queue (section F).
- **Network** — gangs, members and properties as a navigable graph.
- **Narcotics** — drug processing and market analytics. **Ballistics** — weapon benches and component tracing. **M.O. Detector** — tactical profiling and cross-reference.
- **Media Vault** — universal media-to-case intake. **Records** — live shared division records.

### Working with linked records

The registries are relationship-first — a record's value is who and what it's connected to:

- **Edit a link, don't recreate it.** Every relationship (person↔person, person↔vehicle, person↔place, gang turf and properties, gang↔account, gang↔narcotic, case intel links, account ownership) has an **Edit** control: change its confidence, its role or note, or mark it **Current / Historical / Disputed** as the picture develops. An association that ended is marked Historical — not deleted — so the record keeps its history and its audit trail.
- **Search pickers.** Linking a record opens a search picker over the registry — type a few letters and pick — instead of scrolling an unbounded list.
- **Peek before you open.** Linked records carry a **peek** button: a small preview card with the record's identity, status chips and linked-record counts, so you can confirm "is this the right one?" without leaving your screen. One click opens the full record.
- **New link panels**: a vehicle's profile lists its **linked people**, a gang dossier its **accounts** and **narcotics** ties, and an account its **surveillance history** — connections that existed in the data but had no screen before.
- **Duplicate warnings.** Creating a person, gang or vehicle shows an inline warning when a similar record already exists — with peek buttons to check — but never blocks you; you decide.
- **Pin** buttons on person, vehicle, gang, account and narcotics records add them to your Jump-back strip (section C).

Link intel to a case from the case's **Intel & Notes** tab so everything cross-references. **Follow** any case, person or vehicle (the ☆ button) and My Desk flags it whenever it changes — follow is "tell me about changes", pin is "keep it one click away". Archiving hides a record from working views without destroying it; **permanent deletion is the portal owner's alone**.

## I. Reports, evidence and sign-off

### Reports

Write investigative reports on the case's **Reports** tab, from the division's templates. The **Evidence / Property** section has **Add from case evidence** and **Add from case attachments** pickers — they list only what is already logged on this case, and entries appear as removable chips. Open a saved report in place: referenced evidence expands, attachments open, matching names jump to profiles.

**Your draft saves itself.** While you type, a small chip shows **Saving… / Saved** — the draft is stored to your account, so you can start a report at one desk and finish it at another. If you're offline (or the draft grows very large) the chip says so and the draft is kept on the device until it can sync. Reopening the editor shows a **Restore draft** banner — restore it or **Discard** it deliberately; saved drafts also appear in the Action Center's **Drafts** lane. The same autosave runs on case notes, the case chat composer, person and gang creation, and intelligence summaries.

**Finalize** seals the report — contents lock, and your signature (name, badge, time) is recorded. Bureau Leads and above can **Reopen** a sealed report; nothing sealed is ever lost — Signatures shows every seal including superseded ones, and **Versions** lists each sealed version exactly as signed. Warrant reports carry a status ladder (draft → signed → executed → **Return filed**) that feeds the BOLO board and person profiles. "Return filed" means the warrant's return went to the court — the warrant is complete. It is deliberately not called "Returned", which in legal review means **Returned for revision** (sent back to you for changes).

### Charges

An authorized investigator adds a charge from the frozen penal-code snapshot; it is active from that moment. The court lane — filing, conviction, dismissal — belongs to prosecutors and the court, not to CID ranks. Withdrawal stays with the case team.

### Sign-off

When the investigation is done, open **Sign-off** and submit. Routing is automatic — bureau lead → deputy director → director — and **LOA-aware**: an approver on leave is skipped, and the record shows who actually signed. You are notified at every step; returned cases land in **My Desk → Returned or in-flight sign-off** with the reviewer's note. Nobody approves their own submission.

### The case packet

**Case packet** exports the full record as a letterheaded, paginated **PDF** (or DOCX / Markdown), ready for court.

## J. Troubleshooting

| Symptom | What it means — and the fix |
|---|---|
| "Signed in but not yet approved" | Your membership request is pending. Ask Command to review it, then reload. |
| You chose **Submit Intelligence** but see no CID screens | Correct — intelligence-only access is submission-only. If you need investigative access, a Command member must approve a CID membership. |
| A case a colleague mentions isn't there | It belongs to another bureau, or access is scoped away from you. Ask the case lead or your Bureau Lead — access is enforced server-side. |
| A record you saw before is gone | Access can lawfully end (joint-case expiry, restriction). If you believe it's an error, ask your lead — do not assume deletion. |
| An SIB record or investigation is "not found" | You are outside its classification or compartment. If your work genuinely needs it, ask SIB command through your chain. |
| A CID case is read-only in the SIB workspace | Only oversight standing reads CID without writing. Active SIB agents edit CID cases — if you can't, your membership may be suspended or ended. |
| **Save failed / Delete failed** toast | The server refused the write — the message says why. Nothing was silently lost. |
| **Upload failed** | Check the file type (image / video / audio / PDF) and connection, then retry — each file uploads independently. |
| A legal request has vanished from your queue | It moved to the next stage, was claimed by someone else, or is sealed. Check its Review History from the request itself. |
| Your legal request came back | Read the return note on the request, fix the draft, and resubmit. Only declare **material change** if the substance changed — that rewinds it to full command review. |
| Search finds nothing | Fewer letters (it tolerates typos), or a plate / case-number fragment. **Ctrl-K / ⌘K** opens the full palette. |
| Changes elsewhere aren't showing | A connection banner appears when you're offline; reload or click Refresh on My Desk. |
| Archived or deleted something by accident | Most deletions show an **Undo** toast for a few seconds. Archived records are restorable. Cases are archived, not deleted — only the portal owner deletes permanently. Ask Command; everything is audit-logged. |
| You can't approve your own work | By design, everywhere: sign-off, legal review, membership approvals. A second person must act. |

Questions or ideas? Use **Feedback** (sidebar) — it goes to the portal owner, and you can watch its status as it's triaged.
`
